
name: Check Environment Secret

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check Environment Secret
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
      run: |
        if [ "$MY_SECRET" = "SECRET1" ]; then
          echo "Environment secret is correct. Build will succeed."
          exit 0
        else
          echo "Environment secret is incorrect. Build will fail."
          exit 1
        fi